# Generated by Django 5.1.4 on 2025-01-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="news/")),
                ("create_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
